src/Entity/Meal.php
<?php

namespace App\Entity;

use App\Repository\MealRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MealRepository::class)]
class Meal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    private ?string $ingredients = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $preparation = null;

    #[ORM\Column(length: 255)]
    private ?string $rating = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $calories = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $prep_time = null;

    #[ORM\ManyToOne(inversedBy: 'meals')]
    private ?User $creator = null;

    #[ORM\OneToMany(mappedBy: 'fk_meal', targetEntity: Planner::class, orphanRemoval: true)]
    private Collection $fk_meal;

    #[ORM\Column]
    private ?bool $is_verified = false;



    public function __construct()
    {
        $this->fk_meal = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getIngredients(): ?string
    {
        return $this->ingredients;
    }

    public function setIngredients(string $ingredients): static
    {
        $this->ingredients = $ingredients;

        return $this;
    }

    public function getPreparation(): ?string
    {
        return $this->preparation;
    }

    public function setPreparation(string $preparation): static
    {
        $this->preparation = $preparation;

        return $this;
    }

    public function getRating(): ?string
    {
        return $this->rating;
    }

    public function setRating(string $rating): static
    {
        $this->rating = $rating;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCalories(): ?string
    {
        return $this->calories;
    }

    public function setCalories(string $calories): static
    {
        $this->calories = $calories;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getPrepTime(): ?\DateTimeInterface
    {
        return $this->prep_time;
    }

    public function setPrepTime(\DateTimeInterface $prep_time): static
    {
        $this->prep_time = $prep_time;

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): static
    {
        $this->creator = $creator;

        return $this;
    }

    /**
     * @return Collection<int, Planner>
     */
    public function getFkMeal(): Collection
    {
        return $this->fk_meal;
    }

    public function addFkMeal(Planner $fkMeal): static
    {
        if (!$this->fk_meal->contains($fkMeal)) {
            $this->fk_meal->add($fkMeal);
            $fkMeal->setFkMeal($this);
        }

        return $this;
    }

    public function removeFkMeal(Planner $fkMeal): static
    {
        if ($this->fk_meal->removeElement($fkMeal)) {
            // set the owning side to null (unless already changed)
            if ($fkMeal->getFkMeal() === $this) {
                $fkMeal->setFkMeal(null);
            }
        }

        return $this;
    }

    public function isIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): static
    {
        $this->is_verified = $is_verified;

        return $this;
    }
}

src/Form/Planner1Type.php
<?php

namespace App\Form;

use App\Entity\Meal;
use App\Entity\Planner;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Planner1Type extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('time', ChoiceType::class, [
                'attr' => ['class' => 'form-control'],
                'label' => 'Time',
                'choices' => [
                    'Breakfast' => 'Breakfast',
                    'Lunch' => 'Lunch',
                    'Dinner' => 'Dinner'
                ]
            ])
            ->add('day', ChoiceType::class, [
                'attr' => ['class' => 'form-control'],
                'label' => 'Day',
                'choices' => [
                    'Monday' => 'Monday', 
                    'Tuesday' => 'Tuesday', 
                    'Wednesday' => 'Wednesday', 
                    'Thursday' => 'Thursday', 
                    'Friday' => 'Friday', 
                    'Saturday' => 'Saturday', 
                    'Sunday' => 'Sunday', 
                ]
            ])
//             ->add('fk_user', EntityType::class, [
//                 'class' => User::class,
// 'choice_label' => 'username',
//             ])
            //  ->add('fk_meal', EntityType::class, [
            //     'class' => Meal::class,
            //     'attr' => ['class' => 'form-control'],
            //     'label' => 'Change Meal',
            //     'choice_label' => 'name',
            //  ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Planner::class,
        ]);
    }
}

src/Controller/Planner1Controller.php
<?php

namespace App\Controller;

use App\Entity\Planner;
use App\Form\Planner1Type;
use App\Repository\PlannerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/planner1')]
class Planner1Controller extends AbstractController
{
    #[Route('/', name: 'app_planner1_index', methods: ['GET'])]
    public function index( Request $request, PlannerRepository $plannerRepository): Response
    { 
        $MondayBreakfast = [];
        $MondayLunch = [];
        $MondayDinner= [];
            
        $monday = $plannerRepository->findBy(['day' => "Monday", 'fk_user' => $this->getUser()->getId()]);
            foreach($monday as $time){
                
                if($time->getTime() == "Breakfast"){
                    array_push($MondayBreakfast, $time);
                }else if ($time->getTime() == "Lunch"){
                    array_push($MondayLunch, $time);}
                    else if ($time->getTime() == "Dinner"){
                        array_push($MondayDinner, $time);}

            };

        $TuesdayBreakfast = [];
        $TuesdayLunch = [];
        $TuesdayDinner= [];
            $tuesday = $plannerRepository->findBy(['day' => "Tuesday", 'fk_user' => $this->getUser()->getId()]);
         
            foreach($tuesday as $time){
                
                if($time->getTime() == "Breakfast"){
                    array_push($TuesdayBreakfast, $time);
                }else if ($time->getTime() == "Lunch"){
                    array_push($TuesdayLunch, $time);}
                    else if ($time->getTime() == "Dinner"){
                        array_push($TuesdayDinner, $time);}

            };

        $WednesdayBreakfast = [];
        $WednesdayLunch = [];
        $WednesdayDinner= [];
            $wednesday = $plannerRepository->findBy(['day' => "Wednesday", 'fk_user' => $this->getUser()->getId()]);
             
            foreach($wednesday as $time){
                    
                    if($time->getTime() == "Breakfast"){
                        array_push($WednesdayBreakfast, $time);
                    }else if ($time->getTime() == "Lunch"){
                        array_push($WednesdayLunch, $time);}
                        else if ($time->getTime() == "Dinner"){
                            array_push($WednesdayDinner, $time);}
    
                };

                $ThursdayBreakfast = [];
                $ThursdayLunch = [];
                $ThursdayDinner= [];
                    $thursday = $plannerRepository->findBy(['day' => "Thursday", 'fk_user' => $this->getUser()->getId()]);
                     
                    foreach($thursday as $time){
                            
                            if($time->getTime() == "Breakfast"){
                                array_push($ThursdayBreakfast, $time);
                            }else if ($time->getTime() == "Lunch"){
                                array_push($ThursdayLunch, $time);}
                                else if ($time->getTime() == "Dinner"){
                                    array_push($ThursdayDinner, $time);}
            
                        };

        $FridayBreakfast = [];
        $FridayLunch = [];
        $FridayDinner= [];
            $friday = $plannerRepository->findBy(['day' => "Friday", 'fk_user' => $this->getUser()->getId()]);
                 
            foreach($friday as $time){
                        
                if($time->getTime() == "Breakfast"){
                        array_push($FridayBreakfast, $time);
                    }else if ($time->getTime() == "Lunch"){
                        array_push($FridayLunch, $time);}
                    else if ($time->getTime() == "Dinner"){
                        array_push($FridayDinner, $time);}
        
                    };

                    $SaturdayBreakfast = [];
                    $SaturdayLunch = [];
                    $SaturdayDinner= [];
                        $saturday = $plannerRepository->findBy(['day' => "Saturday", 'fk_user' => $this->getUser()->getId()]);
                             
                        foreach($saturday as $time){
                                    
                            if($time->getTime() == "Breakfast"){
                                    array_push($SaturdayBreakfast, $time);
                                }else if ($time->getTime() == "Lunch"){
                                    array_push($SaturdayLunch, $time);}
                                else if ($time->getTime() == "Dinner"){
                                    array_push($SaturdayDinner, $time);}
                    
                                };
                                $SundayBreakfast = [];
                                $SundayLunch = [];
                                $SundayDinner= [];
                                    $sunday = $plannerRepository->findBy(['day' => "Sunday", 'fk_user' => $this->getUser()->getId()]);
                                         
                                    foreach($sunday as $time){
                                                
                                        if($time->getTime() == "Breakfast"){
                                                array_push($SundayBreakfast, $time);
                                            }else if ($time->getTime() == "Lunch"){
                                                array_push($SundayLunch, $time);}
                                            else if ($time->getTime() == "Dinner"){
                                                array_push($SundayDinner, $time);}
                                
                                            };

            
            $tuesday = $plannerRepository->findBy(['day' => "Tuesday", 'fk_user' => $this->getUser()->getId()]);
            $wednesday = $plannerRepository->findBy(['day' => "Wednesday", 'fk_user' => $this->getUser()->getId()]);
            $thursday = $plannerRepository->findBy(['day' => "Thursday", 'fk_user' => $this->getUser()->getId()]);
            $friday = $plannerRepository->findBy(['day' => "Friday", 'fk_user' => $this->getUser()->getId()]);
            $saturday = $plannerRepository->findBy(['day' => "Saturday", 'fk_user' => $this->getUser()->getId()]);
            $sunday = $plannerRepository->findBy(['day' => "Sunday", 'fk_user' => $this->getUser()->getId()]);
       
        return $this->render('planner1/index.html.twig', [
            'monday' => $monday,
            'tuesday' => $tuesday,
            'wednesday' => $wednesday,
            'thursday' => $thursday,
            'friday' => $friday,
            'saturday' => $saturday,
            'sunday' => $sunday,
            "mondayBreakfast"=> $MondayBreakfast,
            "mondayLunch"=> $MondayLunch,
            "mondayDinner"=> $MondayDinner,
            "tuesdayBreakfast"=> $TuesdayBreakfast,
            "tuesdayLunch"=> $TuesdayLunch,
            "tuesdayDinner"=> $TuesdayDinner,
            "wednesdayBreakfast"=> $WednesdayBreakfast,
            "wednesdayLunch"=> $WednesdayLunch,
            "wednesdayDinner"=> $WednesdayDinner,
            "thursdayBreakfast"=> $ThursdayBreakfast,
            "thursdayLunch"=> $ThursdayLunch,
            "thursdayDinner"=> $ThursdayDinner,
            "fridayBreakfast"=> $FridayBreakfast,
            "fridayLunch"=> $FridayLunch,
            "fridayDinner"=> $FridayDinner,
            "saturdayBreakfast"=> $SaturdayBreakfast,
            "saturdayLunch"=> $SaturdayLunch,
            "saturdayDinner"=> $SaturdayDinner,
            "sundayBreakfast"=> $SundayBreakfast,
            "sundayLunch"=> $SundayLunch,
            "sundayDinner"=> $SundayDinner

            

        ]
            // 'planners' => $plannerRepository->findAll(),
            
        );
    }

// This section is not needed but is kept just in case
    // #[Route('/new', name: 'app_planner1_new', methods: ['GET', 'POST'])]
    // public function new(Request $request, EntityManagerInterface $entityManager): Response
    // {
    //     $planner = new Planner();
    //     $plan = $this->createForm(Planner1Type::class, $planner);
    //     $plan->handleRequest($request);

    //     if ($plan->isSubmitted() && $plan->isValid()) {
    //         $entityManager->persist($planner);
    //         $entityManager->flush();

    //         return $this->redirectToRoute('app_planner1_index', [], Response::HTTP_SEE_OTHER);
    //     }

    //     return $this->render('planner1/new.html.twig', [
    //         'planner' => $planner,
    //         'plan' => $plan,
    //     ]);
    // }

    #[Route('/{id}', name: 'app_planner1_show', methods: ['GET'])]
    public function show(Planner $planner): Response
    {
        
        return $this->render('planner1/show.html.twig', [
            'planner' => $planner,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_planner1_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Planner $planner, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Planner1Type::class, $planner);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_planner1_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('planner1/edit.html.twig', [
            'planner' => $planner,
            'plan' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_planner1_delete', methods: ['POST'])]
    public function delete(Request $request, Planner $planner, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$planner->getId(), $request->request->get('_token'))) {

templates/planner1/_delete_form.html.twig
<link rel="stylesheet" href="{{asset("CSS/plannerCSS/style.css")}}">

<form method="post" action="{{ path('app_planner1_delete', {'id': planner.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ planner.id) }}">
	<button class="deleteButton">
		<i class="fa-solid fa-trash-can"></i>
		Delete</button>
</form>

templates/planner1/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Planner
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{asset("CSS/plannerCSS/style.css")}}">
{% endblock %}

{% block body %}
	<div class="mainContainer">
		<div class="editContainer">

			<h1 class="mainTitle">Edit Planner</h1>

			{{ include('meal/_plan.html.twig', {'button_label': 'Update meal plan'}) }}

			<div class="editPlannerBtnHolder">
				{{ include('planner1/_delete_form.html.twig') }}
				<a class="backButton" href="{{ path('app_planner1_index') }}">Back to my planner</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/planner1/new.html.twig
{# {% extends 'base.html.twig' %}

This section is not needed but is kept just in case 

{% block title %}New Planner{% endblock %}

{% block body %}
    <h1>Create new Planner</h1>

    {{ include('planner1/_plan.html.twig') }}

    <a href="{{ path('app_planner1_index') }}">back to list</a>
{% endblock %} #}

templates/planner1/show.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Planner{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{asset("CSS/plannerindexCSS/style.css")}}">
{% endblock %}

{% block body %}
 <div class="mainContainer">
  <div class="container">
    <h1 class="text-center m-4" >Planner</h1>

    <table class="tablePlanner">
        <tbody>
             <tr>
                <th>Id</th>
                <td>{{ planner.id }}</td>
            </tr> 
            <tr>
                <th>Time</th>
                <td class="text-center">{{ planner.time }}</td>
            </tr>
            <tr>
                <th>Day</th>
                <td class="text-center">{{ planner.day }}</td>
            </tr>
            <tr>
            <th>Image</th>
            <td class="text-center"><img width="100px;" height="100px;" src="{{ planner.fkMeal.picture }}" alt="{{ planner.fkMeal.name }}">
            </td>
            </tr>
        </tbody>
    </table>

    <a class="backBtn" href="{{ path('app_planner1_index') }}">Back to list</a>

    <a class="editBtn" href="{{ path('app_planner1_edit', {'id': planner.id}) }}">Edit</a>

    {{ include('planner1/_delete_form.html.twig') }}
    </div>
  </div>
{% endblock %} #}

{% extends 'base.html.twig' %}

{% block title %}Meal
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{asset("CSS/mealShowCSS/style.css")}}">
{% endblock %}

{% block body %}
	<div class="container" style="max-width:900px; min-height:100vh;">
		<h1 class="text-center mainTitle">Meal details</h1>

		<div class='p-2'>
			<div class='card1 h-100'>
				<img src={{ planner.fkMeal.picture }} class='card-img-top object-fit-cover showImg' style='height:30rem;' alt={{ planner.fkMeal.name }}>
				<div class='card-body'>
					<h2 class='card-title my-2'>
						{{ planner.fkMeal.name }}</h2>
					{% set maximum_stars = 5 %}
					{% if planner.fkMeal.rating <= maximum_stars %}
						{% for star in 0..(planner.fkMeal.rating) %}
							{% if star != 0 %}
								<i class="bi bi-star-fill text-warning"></i>
							{% endif %}
						{% endfor %}
						{% if (planner.fkMeal.rating) - (planner.fkMeal.rating|round(0, 'floor')) != 0 %}
							<i class="bi bi-star-half text-warning"></i>
						{% endif %}
						{% for star in 0..(maximum_stars - planner.fkMeal.rating|round(0, 'ceil')) %}
							{% if star != 0 %}
								<i class="bi bi-star emptyStar text-warning"></i>
							{% endif %}
						{% endfor %}
					{% endif %}

					<p class='card-text mt-3'>
						<i class="fa-solid fa-wheat-awn-circle-exclamation"></i>
						<b>Ingredients:</b>
						{{ planner.fkMeal.ingredients }}</p>
					<p class='card-text'>
						<i class="bi bi-info-circle-fill"></i>
						<b>Description:</b>
						{{ planner.fkMeal.description }}</p>
					<p class='card-text'>
						<i class="fa-solid fa-list-check"></i>
						<b>Preparation:</b>
						{{ planner.fkMeal.preparation }}</p>
					<p class='card-text'>
						<i class="fa-solid fa-clock"></i>
						<b>Prep time:</b>
						{{ planner.fkMeal.prepTime ? planner.fkMeal.prepTime|date('H:i') : '' }}
						h/min</p>
					{% if planner.fkMeal.creator %}
						<p class="card-text fw-semibold mt-3">
							<i class="fa-solid fa-user"></i>
							<b>Recipe by:</b>
							{{ planner.fkMeal.creator.username }}</p>
					{% endif %}
					<p class='card-text'>
						<i class="fa-solid fa-fire"></i>
						<b>Calories:</b>
						{{ planner.fkMeal.calories }}</p>
					<p class='card-text'>
						<i class="fa-solid fa-utensils"></i>
						<b>Meal type:</b>
						{{ planner.fkMeal.type }}
					</p>
					<div class="plannerBtnHolder">
						{{ include('planner1/_delete_form.html.twig') }}
						<a class="backButtonPlanner" href="{{ path('app_planner1_index') }}">Back to list</a>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}